spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamebacket
    username: postgres
    password: mdsoln
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always
  address: 0.0.0.0
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
clickSend-username: gamebackets@gmail.com
clickSend-apiKey: 95E02DE1-AD4A-B3A6-3F9E-19F34D86F5DC